# Generated by Django 3.2.4 on 2021-06-25 21:13

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Cadastro ativo')),
                ('dt_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Dt. cadastro')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('idade', models.CharField(max_length=3, verbose_name='Idade')),
                ('cidade', models.CharField(blank=True, max_length=70, null=True, verbose_name='Cidade')),
            ],
            options={
                'ordering': ['nome'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
